name: Deploy Resume Site

on:
  push:
    branches:
      - main

permissions:
  contents: read        # needed to fetch your code
  pages: write          # needed to publish
  id-token: write       # needed to configure the pages environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages              # this ties into your “github-pages” environment
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'                    # your index.html is at the repo root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
